"""add_trade_mode_and_audit_fields

Revision ID: f49a0f90e8a9
Revises: 7403273b52d2
Create Date: 2025-11-14 23:37:33.505949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49a0f90e8a9'
down_revision = '7403273b52d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('order_type', sa.String(), nullable=False))
    op.add_column('trades', sa.Column('mode', sa.String(), nullable=False))
    op.add_column('trades', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('audit_logged', sa.Boolean(), nullable=False))
    op.alter_column('trades', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trades_mode'), 'trades', ['mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_mode'), table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.alter_column('trades', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('trades', 'audit_logged')
    op.drop_column('trades', 'pnl')
    op.drop_column('trades', 'mode')
    op.drop_column('trades', 'order_type')
    # ### end Alembic commands ###

