#!/bin/bash
# Neon Database Setup Script for CryptoOrchestrator
# This script helps configure Neon PostgreSQL database

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Print header
echo -e "\n${BOLD}${BLUE}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${BLUE}║  CryptoOrchestrator - Neon Database Setup          ║${NC}"
echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════════════╝${NC}\n"

# Check if .env exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠ .env file already exists!${NC}"
    read -p "Do you want to overwrite it? (yes/no): " overwrite
    if [[ ! "$overwrite" =~ ^(yes|y|Y|YES)$ ]]; then
        echo -e "${BLUE}ℹ Setup cancelled. Existing .env file preserved.${NC}"
        exit 0
    fi
    echo ""
fi

# Step 1: Get connection string
echo -e "${BOLD}Step 1: Neon Connection String${NC}"
echo -e "${BLUE}ℹ You can find this in your Neon console: https://console.neon.tech${NC}"
echo -e "${BLUE}ℹ Example: postgresql://user:pass@ep-xyz-123.us-east-2.aws.neon.tech/neondb?sslmode=require${NC}"
echo ""

read -p "Enter your Neon connection string: " NEON_CONNECTION_STRING
echo ""

if [ -z "$NEON_CONNECTION_STRING" ]; then
    echo -e "${RED}✗ Connection string cannot be empty!${NC}"
    exit 1
fi

# Step 2: Validate format
echo -e "${BOLD}Step 2: Validating Connection String${NC}"

if [[ ! "$NEON_CONNECTION_STRING" =~ postgresql.* ]]; then
    echo -e "${RED}✗ Invalid connection string format (should start with postgresql://)${NC}"
    exit 1
fi

if [[ ! "$NEON_CONNECTION_STRING" =~ neon\.tech ]]; then
    echo -e "${YELLOW}⚠ Warning: This doesn't appear to be a Neon database URL${NC}"
fi

if [[ ! "$NEON_CONNECTION_STRING" =~ sslmode=require ]]; then
    echo -e "${YELLOW}⚠ Warning: Missing sslmode=require parameter${NC}"
    NEON_CONNECTION_STRING="${NEON_CONNECTION_STRING}?sslmode=require"
fi

echo -e "${GREEN}✓ Valid connection string format${NC}"
echo ""

# Step 3: Generate secrets
echo -e "${BOLD}Step 3: Generating Secure Secrets${NC}"

# Check if openssl is available
if command -v openssl &> /dev/null; then
    JWT_SECRET=$(openssl rand -hex 32)
    JWT_REFRESH_SECRET=$(openssl rand -hex 32)
    ENCRYPTION_KEY=$(openssl rand -hex 16)
elif command -v python3 &> /dev/null; then
    JWT_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
    JWT_REFRESH_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
    ENCRYPTION_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(16))')
else
    echo -e "${RED}✗ Neither openssl nor python3 found. Cannot generate secrets.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ JWT Secret generated${NC}"
echo -e "${GREEN}✓ JWT Refresh Secret generated${NC}"
echo -e "${GREEN}✓ Encryption Key generated${NC}"
echo ""

# Convert to async format for FastAPI
ASYNC_CONNECTION_STRING="${NEON_CONNECTION_STRING//postgresql:\/\//postgresql+asyncpg://}"

# Step 4: Create .env file
echo -e "${BOLD}Step 4: Creating .env File${NC}"

cat > .env << EOF
# CryptoOrchestrator Environment Configuration
# Generated by setup-neon.sh on $(date)

# ============================================
# Database Configuration (Neon PostgreSQL)
# ============================================
# For async operations (FastAPI app) - use asyncpg driver
DATABASE_URL=$ASYNC_CONNECTION_STRING

# ============================================
# Security Secrets
# ============================================
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
EXCHANGE_KEY_ENCRYPTION_KEY=$ENCRYPTION_KEY

# ============================================
# Redis Cache (Optional)
# ============================================
# Get free Redis from Upstash: https://upstash.com
# REDIS_URL=rediss://default:password@endpoint.upstash.io:6379

# ============================================
# Application Configuration
# ============================================
NODE_ENV=development
ENVIRONMENT=development
PORT=8000
HOST=0.0.0.0

# ============================================
# Database Pool Configuration
# ============================================
# Optimized for Neon's connection pooling
DB_POOL_SIZE=20
DB_MAX_OVERFLOW=10
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=3600

# ============================================
# CORS Configuration
# ============================================
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000

# ============================================
# Feature Flags
# ============================================
USE_MOCK_KRAKEN=false
ENABLE_DISTRIBUTED_RATE_LIMIT=false

# ============================================
# Logging
# ============================================
LOG_LEVEL=INFO

# ============================================
# Optional: Payment Processing (Stripe)
# ============================================
# STRIPE_SECRET_KEY=sk_test_your_key_here
# STRIPE_WEBHOOK_SECRET=whsec_your_secret_here
# STRIPE_PUBLISHABLE_KEY=pk_test_your_key_here

# ============================================
# Optional: Error Tracking (Sentry)
# ============================================
# SENTRY_DSN=https://your_sentry_dsn_here

# ============================================
# Optional: Exchange API Keys
# ============================================
# Only required for live trading
# KRAKEN_API_KEY=your_api_key
# KRAKEN_SECRET_KEY=your_secret_key
# BINANCE_API_KEY=your_api_key
# BINANCE_SECRET_KEY=your_secret_key
EOF

echo -e "${GREEN}✓ Created .env file${NC}"
echo ""

# Step 5: Update alembic.ini
echo -e "${BOLD}Step 5: Updating Alembic Configuration${NC}"

if [ -f "alembic.ini" ]; then
    # Convert back to sync format for Alembic
    SYNC_CONNECTION_STRING="${NEON_CONNECTION_STRING//postgresql+asyncpg:\/\//postgresql://}"
    
    # Use sed to replace the sqlalchemy.url line
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^sqlalchemy.url = .*|sqlalchemy.url = $SYNC_CONNECTION_STRING|" alembic.ini
    else
        # Linux
        sed -i "s|^sqlalchemy.url = .*|sqlalchemy.url = $SYNC_CONNECTION_STRING|" alembic.ini
    fi
    
    echo -e "${GREEN}✓ Updated alembic.ini${NC}"
else
    echo -e "${YELLOW}⚠ alembic.ini not found, skipping update${NC}"
fi
echo ""

# Final success message
echo -e "${BOLD}${GREEN}✓ Setup Complete!${NC}\n"
echo -e "${BOLD}Next Steps:${NC}"
echo -e "  1. Review and update the .env file with any optional settings"
echo -e "  2. Run database migrations: ${BLUE}npm run migrate${NC}"
echo -e "  3. Start the development server: ${BLUE}npm run dev:fastapi${NC}"
echo ""
echo -e "${BOLD}Optional:${NC}"
echo -e "  • Set up Redis cache (Upstash free tier): https://upstash.com"
echo -e "  • Configure Stripe for payments (if needed)"
echo -e "  • Add exchange API keys for live trading"
echo ""
echo -e "${BOLD}Documentation:${NC}"
echo -e "  • Neon Setup Guide: ${BLUE}docs/NEON_SETUP.md${NC}"
echo -e "  • Free Stack Deployment: ${BLUE}docs/FREE_STACK_DEPLOYMENT.md${NC}"
echo ""
